12: 'audio_stim/pau.wav'
7: 'audio_stim/to.wav'
9: 'audio_stim/ne.wav'

11: 'audio_stim/nu.wav'
1: 'audio_stim/ra.wav'
8: 'audio_stim/fi.wav'

5: 'audio_stim/mai.wav'
4: 'audio_stim/lo.wav'
2: 'audio_stim/ki.wav'

10: 'audio_stim/ga.wav'
3: 'audio_stim/ba.wav'
6: 'audio_stim/lu.wav'
