- dots:
  num_dots: 12
  dot_space: 180
  dot_size: 36
  dot_start: [(w+dot_space*i,half_height) for i in range(num_dots)] # starting dot positions
  dot_posn: dot_start
  freq: float(input("Type in the frequency:")) # user defined dot freq for testing
- format:
  w: 900
  h: 600
  half_height: int(h/2)
  left_position: 180
  frame_rate: 45
- time:
  times: [None for dot in dot_posn]
  t_fin: (num_dots+w/dot_space)/freq
